'use client';

import { MapPinned, Search, SlidersHorizontal, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { apiUrl } from './aws-client';
import { HairstyleCard, ProductCard, StylistCard } from './marketplace-components';
import { looks, products, stylists } from './marketplace-data';

function initialQuery() { if (typeof window === 'undefined') return ''; return new URLSearchParams(window.location.search).get('q') ?? ''; }
function LiveInput({ value, onChange, placeholder }: { value:string; onChange:(value:string)=>void; placeholder:string }) { return <label className="live-search"><Search/><input value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} aria-label={placeholder}/>{value&&<button type="button" onClick={()=>onChange('')} aria-label="Clear search"><X/></button>}<span>Live results</span></label> }
function EmptyResults({ onClear }: { onClear:()=>void }) { return <div className="search-empty"><Search/><h3>No matches found</h3><p>Try a different hairstyle, product, stylist or location.</p><button className="cc-button outline" onClick={onClear}>Clear filters</button></div> }

export function DiscoverSearch() {
  const [query,setQuery]=useState(initialQuery); const [category,setCategory]=useState('For you');
  const results=useMemo(()=>looks.filter(look=>{const text=`${look.name} ${look.stylist} ${look.location}`.toLowerCase();const matchesQuery=text.includes(query.trim().toLowerCase());const matchesCategory=category==='For you'||category==='Trending'||(category==='Braids'&&look.name.toLowerCase().includes('braid'))||(category==='Natural hair'&&look.name.toLowerCase().includes('natural'))||(category==='Locs'&&look.name.toLowerCase().includes('loc'))||(category==='Cornrows'&&look.name.toLowerCase().includes('cornrow'))||(category==='Wigs'&&look.name.toLowerCase().includes('press'));return matchesQuery&&matchesCategory}),[query,category]);
  return <><LiveInput value={query} onChange={setQuery} placeholder="Search hairstyles, stylists or locations…"/><div className="feed-tabs">{['For you','Trending','Braids','Wigs','Natural hair','Locs','Cornrows'].map(item=><button className={category===item?'active':''} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><p className="live-count" aria-live="polite">{results.length} {results.length===1?'look':'looks'} found</p>{results.length?<div className="discover-grid">{results.map(look=><HairstyleCard key={look.slug} look={look}/>)}</div>:<EmptyResults onClear={()=>{setQuery('');setCategory('For you')}}/>}</>;
}

export function ShopSearch() {
  const [query,setQuery]=useState(initialQuery); const [category,setCategory]=useState('All products'); const [sort,setSort]=useState('featured');
  const results=useMemo(()=>products.filter(product=>`${product.name} ${product.category}`.toLowerCase().includes(query.trim().toLowerCase())).filter(product=>category==='All products'||product.category.toLowerCase().includes(category.toLowerCase().replace('styling products','styling'))).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.rating-a.rating),[query,category,sort]);
  return <><div className="search-toolbar"><LiveInput value={query} onChange={setQuery} placeholder="Search wigs, braids, bundles and hair care…"/><label>Sort<select value={sort} onChange={event=>setSort(event.target.value)}><option value="featured">Top rated</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div className="filter-pills">{['All products','Wigs','Braids','Extensions','Bundles','Hair care','Styling'].map(item=><button className={category===item?'active':''} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><p className="live-count" aria-live="polite">{results.length} products available</p>{results.length?<div className="product-grid large">{results.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<EmptyResults onClear={()=>{setQuery('');setCategory('All products')}}/>}</>;
}

type LiveStylist=(typeof stylists)[number];
export function StylistSearch() {
  const [query,setQuery]=useState(initialQuery); const [service,setService]=useState('All services'); const [maxPrice,setMaxPrice]=useState('any'); const [minRating,setMinRating]=useState('0'); const [maxDistance,setMaxDistance]=useState('any'); const [liveStylists,setLiveStylists]=useState<LiveStylist[]>(stylists); const [loading,setLoading]=useState(true);
  useEffect(()=>{void fetch(`${apiUrl}/sellers`).then(response=>response.ok?response.json():Promise.reject()).then(data=>{const remote:LiveStylist[]=(data.sellers??[]).map((seller:{id:string;business_name:string;city:string;specialty:string;service_price:number},index:number)=>({id:Number(seller.id),name:seller.business_name,location:seller.city,distance:index===0?'2.3 km':`${3+index}.1 km`,rating:4.8,reviews:24+index*11,price:Number(seller.service_price),specialties:seller.specialty,cell:(index+1)%6}));setLiveStylists([...remote,...stylists.filter(sample=>!remote.some(item=>item.id===sample.id))])}).catch(()=>setLiveStylists(stylists)).finally(()=>setLoading(false))},[]);
  const results=useMemo(()=>liveStylists.filter(stylist=>`${stylist.name} ${stylist.location} ${stylist.specialties}`.toLowerCase().includes(query.trim().toLowerCase())).filter(stylist=>service==='All services'||stylist.specialties.toLowerCase().includes(service.toLowerCase())).filter(stylist=>maxPrice==='any'||stylist.price<=Number(maxPrice)).filter(stylist=>stylist.rating>=Number(minRating)).filter(stylist=>maxDistance==='any'||Number.parseFloat(stylist.distance)<=Number(maxDistance)),[query,service,maxPrice,minRating,maxDistance,liveStylists]);
  const clear=()=>{setQuery('');setService('All services');setMaxPrice('any');setMinRating('0');setMaxDistance('any')};
  return <><LiveInput value={query} onChange={setQuery} placeholder="Search stylist, service or location…"/><div className="real-filters"><span><SlidersHorizontal/> Filters</span><label>Distance<select value={maxDistance} onChange={event=>setMaxDistance(event.target.value)}><option value="any">Any distance</option><option value="3">Within 3 km</option><option value="5">Within 5 km</option><option value="10">Within 10 km</option></select></label><label>Service<select value={service} onChange={event=>setService(event.target.value)}><option>All services</option><option>Braids</option><option>Cornrows</option><option>Wigs</option><option>Silk press</option><option>Locs</option><option>Natural hair</option></select></label><label>Max price<select value={maxPrice} onChange={event=>setMaxPrice(event.target.value)}><option value="any">Any price</option><option value="350">Up to R350</option><option value="450">Up to R450</option><option value="600">Up to R600</option></select></label><label>Rating<select value={minRating} onChange={event=>setMinRating(event.target.value)}><option value="0">Any rating</option><option value="4.5">4.5+</option><option value="4.8">4.8+</option></select></label><button onClick={clear}>Clear all</button></div><p className="live-count" aria-live="polite">{loading?'Updating from CrownConnect…':`${results.length} stylists match your search`}</p><div className="stylist-search-layout">{results.length?<div className="stylist-results">{results.map(stylist=><StylistCard key={stylist.id} stylist={stylist}/>)}</div>:<EmptyResults onClear={clear}/>}<aside className="map-mock"><div className="map-road one"/><div className="map-road two"/><div className="map-road three"/>{results.slice(0,4).map((stylist,index)=><span key={stylist.id} className={`map-pin pin-${index}`}><MapPinned/> R{stylist.price}</span>)}<div className="map-label">Pretoria</div></aside></div></>;
}
